name: nightly

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        env: 
          URL: ${{ secrets.NETLIFY_NIGHTLY_HOOK_URL }}
        run: |
          echo "the var is $env"
          curl -X POST -d '{}' $URL
